{{- if .Values.secenv -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "de-design-library.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "de-design-library.name" . }}
    helm.sh/chart: {{ include "de-design-library.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- range $k, $v := .Values.secenv }}
  {{ $k }}: {{ $v | toString | b64enc }}
  {{- end }}
{{- end -}}
